### ISSUE TITLE
`fprime-cli` not working

### ISSUE THREAD

**Issue by thomas-bc** [nasa/fprime-gds#112]
| | |
|:---|:---|
|**_F´ Version_**| `devel` |
|**_Affected Component_**| `fprime-cli`  |
---
## Problem Description

`fprime-cli events` is not working properly in the current devel version. I haven't been able to investigate more.

## How to Reproduce

1.  checkout fprime-gds:devel
2. `pip install .` to install
3. `fprime-cli events`
errors out with:

```
$ fprime-cli events
Traceback (most recent call last):
  File "/Users/chammard/Work/fprime/fprime/Ref/old_env/bin/fprime-cli", line 33, in <module>
    sys.exit(load_entry_point('fprime-gds==3.1.5a2.dev5+g7382c8c.d20230125', 'console_scripts', 'fprime-cli')())
  File "/Users/chammard/Work/fprime/fprime/Ref/old_env/lib/python3.8/site-packages/fprime_gds/executables/fprime_cli.py", line 399, in main
    args = parse_args(parser, sys.argv[1:])
  File "/Users/chammard/Work/fprime/fprime/Ref/old_env/lib/python3.8/site-packages/fprime_gds/executables/fprime_cli.py", line 390, in parse_args
    args = args.validate(parser, args)
  File "/Users/chammard/Work/fprime/fprime/Ref/old_env/lib/python3.8/site-packages/fprime_gds/executables/fprime_cli.py", line 186, in validate_args
    args = add_valid_dictionary(args)
  File "/Users/chammard/Work/fprime/fprime/Ref/old_env/lib/python3.8/site-packages/fprime_gds/executables/fprime_cli.py", line 138, in add_valid_dictionary
    args.dictionary = get_dictionary_path(args)
  File "/Users/chammard/Work/fprime/fprime/Ref/old_env/lib/python3.8/site-packages/fprime_gds/executables/fprime_cli.py", line 128, in get_dictionary_path
    args = GdsParser.handle_arguments(args, kwargs={})
TypeError: handle_arguments() missing 1 required positional argument: 'args'
```

## Expected Behavior

Waiting for an event, no error showing up.

**Comment by thomas-bc** [comment]
Turns out this also affects `events` and `channels`
